name: Build Wheel for py_find_1st

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        python-version: ['3.12']

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel setuptools

    - name: Build the wheel
      run: |
        python setup.py sdist bdist_wheel

    - name: Upload the wheel
      uses: actions/upload-artifact@v2
      with:
        name: wheel
        path: dist/*.whl
